nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
    'babel-loader@*':
        peerDependenciesMeta:
            '@babel/core':
                optional: true
            'webpack':
                optional: true
    'clean-webpack-plugin@*':
        peerDependenciesMeta:
            'webpack':
                optional: true
    'terser-webpack-plugin@*':
        peerDependenciesMeta:
            'webpack':
                optional: true
    'workbox-webpack-plugin@*':
        peerDependenciesMeta:
            'webpack':
                optional: true
